### ISSUE TITLE
Access to host dconf

### ISSUE THREAD

**Issue by bbhtt** [flathub/io.github.vikdevelop.SaveDesktop#90]
Hey, @vikdevelop direct access to host dconf is going to get blocked by the linter soon.

This manifest uses it

https://github.com/flathub/io.github.vikdevelop.SaveDesktop/blob/5f746b69ba9efeeb58b4bc6e9e15e0827c08d6b4/io.github.vikdevelop.SaveDesktop.yaml#L47-L49

Can you please say why this is needed? The commit here says nothing https://github.com/flathub/io.github.vikdevelop.SaveDesktop/commit/930d893fb5eff977bd0faf469259b9377e650478

**Comment by vikdevelop** [comment]
Hello, this function is necessary for proper functionality of the app. It allows to save and import all data in the dconf database. 

I introduced this function after saving the `~/.config/dconf/user` file was not reliable, because in many cases the configuration was not restored correctly and also it was necessary to log out after importing the configuration.

**Comment by bbhtt** [comment]
Added to exceptions.
